# Generated by Django 3.1.2 on 2023-02-08 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20230208_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='scopes',
            field=models.ManyToManyField(related_name='tag', through='articles.TagsTitle', to='articles.Tag', verbose_name='Раздел'),
        ),
    ]
